task:
  name: Build (Alpine Linux)
  container:
    image: alpine:3.12
    cpu: 8
  environment:
    RUSTFLAGS: "-C target-feature=-crt-static"
    PATH: "$HOME/.cargo/bin:$PATH"
  cargo_cache:
    folder: $HOME/.cargo/registry
    # fingerprint_script: cat Cargo.lock
  install_script:
    - apk update && apk add curl git gcc musl-dev
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain 1.47.0
  test_script:
    - bin/test
    - cargo test
  before_cache_script: rm -rf $HOME/.cargo/registry/index
